[package]
name = "imsub-standalone"
version = "0.1.0"
edition = "2021"
authors = ["Alessandro Grassi <alessandrograssi17@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
toml = "0.5"
serde = "1.0"
clap = "4.0"
