[log]
level = "INFO"
path = "./logs"

[schedule]
time = 14:38:00

[telegram]
token = "2012545650:AAF8WaC2DIsbLM0kKUkpiCxN5B9qf3NLwR4"
groups = [-123456789]
developers = [181213130]

[twitch]
streamer = "227959"
client_id = "iiohejrjhkrj2342343"
client_secret = "139203912"
redirect_uri = "https://alessandrograssi.me/twitch_oauth"

[rabbitmq]
host = "rabbitmq.telegram.rabbitmq"
port = 5671
ca_cert = ""
client_cert = ""
client_key = ""

[database]
host = "75.119.155.136"
port = 3306
username = "root"
password = "mypass"
database = "pippo"

[locale]
path = "./res/locale"
default_lang = "en"
